const arrayOfVans = [
  {
    id: 1,
    name: "Grand California",
    description: "Stylish",
    price: "$150 per night",
    startDate:" ",
    endDate:" ",
    cost: 150,
    image: "fleet6.jpg",
  },
  {
    id: 2,
    name: "Bay Window Camper",
    description: "Hit the road jack",
    price: "$80 per night",
    startDate:" ",
    endDate:" ",
    cost: 80,
    image: "fleet1.jpg",
  },
  {
    id: 3,
    name: "Retro Electric Camper",
    description: "Vintage yet modern",
    price: "$100 per night",
    startDate:" ",
    endDate:" ",
    cost: 100,
    image: "fleet2.jpg",
  },
  {
    id: 4,
    name: "Modern",
    description: "Camping in the 21st century",
    price: "$125 per night",
    startDate:" ",
    endDate:" ",
    cost: 125,
    image: "fleet5.png",
  },
  {
    id: 5,
    name: "Vintage Camper",
    description: "For the retro lovers",
    price: "$50 per night",
    startDate:" ",
    endDate:" ",
    cost: 50,
    image: "fleet5.jpg",
  },
  {
    id: 6,
    name: "Home Comfort",
    description: "All the comforts you need on the road",
    price: "$125 per night",
    startDate:" ",
    endDate:" ",
    cost: 125,
    image: "fleet7.jpg",
  },
];
 export default arrayOfVans ;