const arrayOfVans = [
  {
    id: 1,
    name: "Grand Cali",
    description: "Stylish",
    price: "$150 per night",
    startDate:" ",
    endDate:" ",
    cost: 150,
    image: "fleet6.jpg",
  },
  {
    id: 2,
    name: "Bay Window",
    description: "Hit the road jack",
    price: "$80 per night",
    startDate:" ",
    endDate:" ",
    cost: 80,
    image: "fleet1.jpg",
  },
  {
    id: 3,
    name: "Retro Electric",
    description: "The 70's are back",
    price: "$100 per night",
    startDate:" ",
    endDate:" ",
    cost: 100,
    image: "fleet2.jpg",
  },
  {
    id: 4,
    name: "Modern",
    description: "Camping in 2077",
    price: "$125 per night",
    startDate:" ",
    endDate:" ",
    cost: 125,
    image: "fleet5.png",
  },
  {
    id: 5,
    name: "Vintage",
    description: "Nostalgia",
    price: "$50 per night",
    startDate:" ",
    endDate:" ",
    cost: 50,
    image: "fleet5.jpg",
  },
  {
    id: 6,
    name: "Home",
    description: "House on wheels",
    price: "$125 per night",
    startDate:" ",
    endDate:" ",
    cost: 125,
    image: "fleet7.jpg",
  },
];
 export default arrayOfVans ;